[package]
name = "anthropic"
version = "0.0.6"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
edition = "2021"
license = "MIT"
homepage = "https://github.com/abdelhamidbakhta/anthropic-rs"
repository = "https://github.com/abdelhamidbakhta/antrhopic-rs"
categories = ["api-bindings", "web-programming", "asynchronous"]
keywords = ["anthropic", "async", "ai", "gpt", "claude"]
description = "Anthropic Rust SDK."
readme = "README.md"

[features]
default = ["rustls"]
# Enable rustls for TLS support
rustls = ["reqwest/rustls-tls-native-roots"]
# Enable native-tls for TLS support
native-tls = ["reqwest/native-tls"]

[dependencies]
backoff = {version = "0.4.0", features = ["tokio"] }
config = "0.13.3"
dotenv = "0.15.0"
derive_builder = "0.12.0"
env_logger = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.17"
reqwest = { version = "0.11.17", features = ["json", "stream", "multipart"],default-features = false }
serde = "1.0.163"
serde_derive = "1.0.163"
serde_json = "1.0.96"
tokio = { version = "1", features = ["full"] }
thiserror = "1.0.40"
rustc_version = "0.4.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy"]
